version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "800:80"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build: ./backend
    ports:
      - "7001:7001"
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:5.7 # 使用官方MySQL 5.7镜像
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Misaka20001 # 设置root用户的密码
      MYSQL_DATABASE: map # 创建并使用名为mydatabase的数据库
    ports:
      - "3306:3306" # 将容器的3306端口映射到宿主机的127.0.0.1的3306端口
    volumes:
      - db_data:/var/lib/mysql # 持久化MySQL数据
    networks:
      - webnet

volumes:
  db_data:
    # 定义一个卷来持久化MySQL数据

networks:
  webnet: # 定义一个名为webnet的网络，用于前端和后端服务之间的通信